spring.application.name=backend

# Kết nối tới PostgreSQL thông qua Docker Network
spring.datasource.url=jdbc:postgresql://rikkei_prod:5432/rikkei_prod
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình context path cho các API Request
server.servlet.context-path=/api
